# Generated by Django 4.1.2 on 2022-10-10 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('user_commented', models.CharField(max_length=64)),
                ('listing', models.CharField(max_length=64)),
                ('user_listed', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.URLField(blank=True, max_length=250)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('tag', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=64)),
            ],
        ),
    ]
