# Generated by Django 4.1.2 on 2022-10-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_listed',
            new_name='user_listing',
        ),
    ]
