# Generated by Django 4.1.2 on 2022-10-11 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_category_alter_listings_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
