# Generated by Django 4.1.2 on 2022-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_date_time_alter_listings_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
