# Generated by Django 4.1.2 on 2022-10-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='tag',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
