# Generated by Django 4.1.2 on 2022-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_listings_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('watchlist', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_price',
            new_name='price',
        ),
    ]
