# Generated by Django 4.1.2 on 2022-10-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlists_rename_bid_price_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
