# Generated by Django 4.1.2 on 2022-11-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlists_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
