# Generated by Django 4.1.2 on 2022-11-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='user',
            field=models.CharField(default='user', max_length=64),
        ),
    ]
