# Generated by Django 4.1.2 on 2022-11-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_watchlists_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='listing',
            new_name='list_author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_listing',
            new_name='list_title',
        ),
    ]
