# Generated by Django 4.1.2 on 2022-11-14 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_listing_comments_list_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
