# Generated by Django 4.1.2 on 2022-11-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_comments_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
