# Generated by Django 4.1.2 on 2022-11-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
